# -*- coding: utf-8 -*-
"""CleaningWeather2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_2vBLoZjgPfh-HFiYH02xRu9lt-2fZos
"""

import pandas as pd
from google.colab import files
uploaded=files.upload()

weather= pd.read_csv('updated_weatherr.csv')
print(weather)

"""cleaning the weather column"""

# Find and return all unique values in the 'Weather' column
unique_weather_values = weather['Weather'].unique()

# Display the unique weather values with each item on a new line
for value in unique_weather_values:
    print(f"'{value}': '',")

weather_mapping = {
'Mostly Cloudy': 'Dry',
'Overcast': 'Dry',
'Fair': 'Dry',
'Light Rain': 'Rain',
'A Few Clouds': 'Dry',
'Partly Cloudy': 'Dry',
'Fog/Mist': 'Dry',
'Light Rain Fog/Mist': 'Rain',
'Clear': 'Dry',
'Overcast With Haze': 'Dry',
'Rain Fog/Mist': 'Rain',
'Partly Sunny': 'Dry',
'Overcast And Breezy': 'Dry',
'Overcast And Windy': 'Dry',
'Fog': 'Dry',
'Few Clouds': 'Dry',
'Light Snow Fog/Mist': 'Snow',
'Snow': 'Snow',
'Chance Rain Showers': 'Rain',
'Slight Chance Rain Showers': 'Rain',
'A Few Clouds With Haze': 'Dry',
'Mostly Sunny': 'Dry',
'Mostly Cloudy And Breezy': 'Dry',
'Partly Cloudy With Haze': 'Dry',
'Partly Cloudy And Breezy': 'Dry',
'Fair With Haze': 'Dry',
'Mostly Cloudy And Windy': 'Dry',
'Rain Showers': 'Rain',
'Light Drizzle': 'Rain',
'Sunny': 'Dry',
'Light Rain And Breezy': 'Rain',
'Light Snow': 'Snow',
'Chance Thunderstorms': 'Rain',
'Patchy Fog': 'Dry',
'Thunderstorm In Vicinity Light Rain Fog/Mist': 'Rain',
'Fair And Breezy': 'Dry',
'Lt Rain': 'Rain',
'Rain Fog/Mist And Breezy': 'Rain',
'Thunderstorm Light Rain': 'Rain',
'Light Rain Fog': 'Rain',
'Heavy Snow Freezing Fog': 'Snow',
'Lt Rain, Fog': 'Rain',
'Raining': 'Rain',
'Blowing Snow And Breezy': 'Snow',
'Thunderstorm Rain Fog/Mist': 'Rain',
'Thunder, Lt Rain': 'Rain',
'Mostly Clear': 'Dry',
'Areas Drizzle': 'Rain',
'Breezy': 'Dry',
'Snow And Breezy': 'Snow',
'Chance Snow': 'Snow',
'Areas Fog': 'Dry',
'Light Freezing Rain': 'Rain',
'Wintry Mix': 'Snow',
'Showers': 'Rain',
'Heavy Rain Fog/Mist': 'Rain',
'Thunderstorm': 'Rain',
'Showers In Vicinity': 'Rain',
'Light Drizzle Fog/Mist': 'Rain',
'Cloudy': 'Dry',
'Chance Showers': 'Rain',
'Mod Rain, Fog': 'Rain',
'Thunderstorm Heavy Rain Fog/Mist': 'Rain',
'Drizzle': 'Rain',
'Dry And Partly Cloudy': 'Dry',
'Humid And Mostly Cloudy': 'Dry',
'Humid': 'Dry',
'Foggy': 'Dry',
'Heavy Rain': 'Rain',
'Possible Drizzle': 'Rain',
'Possible Light Rain': 'Rain',
'Humid And Partly Cloudy': 'Dry',
'Flurries': 'Snow',
'Breezy And Humid': 'Dry',
'Humid And Overcast': 'Dry',
'Light Sleet': 'Snow',
'Windy And Partly Cloudy': 'Dry',
'Windy And Overcast': 'Dry',
'Light Rain And Windy': 'Rain',
'Rain And Windy': 'Rain',
'Possible Flurries': 'Snow',
'Light Snow And Windy': 'Snow',
'Possible Light Snow': 'Snow',
'Heavy Snow': 'Snow',
'Likely Rain': 'Rain'
}

# Replace values in the 'Weather' column
weather['Weather'] = weather['Weather'].replace(weather_mapping)

print(weather)

# Find and return all unique values in the 'Weather' column
unique_weather_values = weather['Weather'].unique()

# Display the unique weather values
print(unique_weather_values)

weather.to_csv('total_games_weather.csv', index=False)

from google.colab import files
uploaded=files.upload()

team_names= pd.read_csv('nfl_teams.csv')
print(team_names)

team_names = team_names.drop(['Conference', 'Division'], axis=1)

team_names['Name'] = team_names['Name'].apply(lambda x: x.split()[-1])

# Display the modified DataFrame
print(team_names)

# Separate DataFrames for Team1 and Team2
team1_df = weather[['Season', 'Week', 'Team1', 'Weather']].rename(columns={'Team1': 'Team'})
team2_df = weather[['Season', 'Week', 'Team2', 'Weather']].rename(columns={'Team2': 'Team'})

# Concatenate the two DataFrames
result_df = pd.concat([team1_df, team2_df], ignore_index=True)

# Sort the DataFrame for better organization (optional)
result_df = result_df.sort_values(by=['Season', 'Week'])

# Display the modified DataFrame
print(result_df)

unique_teams = result_df['Team'].unique()

# Display unique team values
print(unique_teams)

result_df['Team'] = result_df['Team'].replace('Washington', 'Commanders')

merged_df = pd.merge(result_df, team_names[['Name', 'Abbreviation']], left_on='Team', right_on='Name', how='left')

# Drop the 'Name' column as it's no longer needed
merged_df = merged_df.drop(['Name'], axis=1)

# Display the modified DataFrame
print(merged_df)

for column in merged_df.columns:
    null_count = merged_df[column].isnull().sum()
    if null_count > 0:
        print(f"Column '{column}' has {null_count} null values.")

null_values = merged_df[merged_df.isnull().any(axis=1)]

# Display rows with null values
print(null_values)

print(merged_df)

from google.colab import files
uploaded=files.upload()

player_info= pd.read_csv('updated_injury_player_data.csv')
print(player_info)

unique_teams = player_info['team'].unique()
num_unique_teams = player_info['team'].nunique()

# Display unique team values and the number of unique values
print("Unique Teams:", unique_teams)
print("Number of Unique Teams:", num_unique_teams)

"""notice in this df, the rams are called LAR... in our updated_player_injury_info dataframe, the rams are LA..


oak ---> oakland raiders ----> LV

sd --> san diego chargers --> los angeles chrgers ---> LAC

in our original  updated player info dataframe


replace all oak values with LV


replace all  los angeles rams LA value with LAR


replace all SD chargers with LA chargers.... as they are the same team that have been moved back and forth in location...  with LAC
"""

player_info['team'] = player_info['team'].replace({'OAK': 'LV', 'LA': 'LAR', 'SD': 'LAC'})

unique_teams = player_info['team'].unique()
num_unique_teams = player_info['team'].nunique()

# Display unique team values and the number of unique values
print("Unique Teams:", unique_teams)
print("Number of Unique Teams:", num_unique_teams)

"""STL TEAM --> st louis rams ----> became the  Los angeles Rams --> should be LAR"""

player_info['team'] = player_info['team'].replace({ 'STL': 'LAR'})

# Display the modified DataFrame
print(player_info)

unique_teams = player_info['team'].unique()
num_unique_teams = player_info['team'].nunique()

# Display unique team values and the number of unique values
print("Unique Teams:", unique_teams)
print("Number of Unique Teams:", num_unique_teams)

print(team_names)

"""Now that we have all the team values in our player info db to match our team values in the  weather df. we can do a join to add teh weather column."""

print(merged_df)

df = merged_df.drop(['Team'], axis=1)  # Remove the 'Team' column

print(df)

df = df.rename(columns={'Abbreviation': 'team'})  # Rename 'Abbreviation' to 'Team'
df = df.rename(columns={'Weather': 'weather'})
df = df.rename(columns={'Week': 'week'})
df = df.rename(columns={'Season': 'season'})
df = df.rename(columns={'Team': 'team'})
# Display the modified DataFrame

print(df)

import pandas as pd

# Assuming your DataFrame is named 'df'
for index, row in df.iterrows():
    if pd.isnull(row['weather']):
        print(f"Null weather value found in Season {row['season']}, Week {row['week']} for Team {row['team']}")

print("no null values in weather")

player_info_merged = pd.merge(player_info, df[['season', 'week', 'team', 'weather']], on=['season', 'week', 'team'], how='left')

# Display the modified DataFrame
print(player_info_merged)

player_info_merged.to_csv('player_injury_age_weather.csv', index=False)

"""

---

"""

# Find rows with null values in the 'Weather' column
null_weather_rows = player_info_merged[player_info_merged['weather'].isnull()]

# Display specific columns for rows with null values in the 'Weather' column
print("Rows with Null Values in Weather:")
print(null_weather_rows[['season', 'week', 'team', 'weather']])

condition = (player_info_merged['season'] == 2009) & (player_info_merged['week'] == 1) & player_info_merged['weather'].isnull()

# Remove rows based on the condition
player_info_merged = player_info_merged[~condition]

# Display the updated DataFrame
print(player_info_merged)

"""

---

**2009**"""

null_values_2009 = player_info_merged[(player_info_merged['season'] == 2009) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2009)

"""using the website for week 18,19,20,21.....
https://www.nflweather.com/week/2009/wildcard-weekend

in 2009, during these weeks all games were sunny or cloudy. so we will give value of dry
"""

player_info_merged.loc[(player_info_merged['season'] == 2009) & (player_info_merged['week'] == 18) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2009) & (player_info_merged['week'] == 19) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2009) & (player_info_merged['week'] ==20) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2009) & (player_info_merged['week'] ==21) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2009 = player_info_merged[(player_info_merged['season'] == 2009) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2009)

"""

---

**2010**"""

null_values_2010 = player_info_merged[(player_info_merged['season'] == 2010) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2010)

player_info_merged.loc[(player_info_merged['season'] == 2010) & (player_info_merged['week'] == 18) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2010) & (player_info_merged['week'] == 19) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2010) & (player_info_merged['week'] == 20) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2010) & (player_info_merged['week'] == 21) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2010 = player_info_merged[(player_info_merged['season'] == 2010) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2010)

"""

---

**2011**"""

null_values_2011 = player_info_merged[(player_info_merged['season'] == 2011) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2011)

player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 18) &  (player_info_merged['team']=='DET') &(player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 18) &  (player_info_merged['team']=='NO') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'

player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

weather_value = player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 18) & (player_info_merged['team'] == 'DET'), 'weather'].iloc[0]

# Display the weather value
print("Weather for 2011 Week 18 Team DET:", weather_value)

player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 19) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'



player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 20) & (player_info_merged['team']=='NY') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 20) & (player_info_merged['team']=='SF') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 20) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'


player_info_merged.loc[(player_info_merged['season'] == 2011) & (player_info_merged['week'] == 21) & (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2011 = player_info_merged[(player_info_merged['season'] == 2011) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2011)

"""

---
**2012**
"""

null_values_2012 = player_info_merged[(player_info_merged['season'] == 2012) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2012)

player_info_merged.loc[(player_info_merged['season'] == 2012) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2012) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2012) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2012) & (player_info_merged['week'] == 21) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2012 = player_info_merged[(player_info_merged['season'] == 2012) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2012)

"""

---
**2013**
"""

null_values_2013 = player_info_merged[(player_info_merged['season'] == 2013) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2013)

player_info_merged.loc[(player_info_merged['season'] == 2013) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2013 = player_info_merged[(player_info_merged['season'] == 2013) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2013)

"""missing values for week 19 20 so we will need to  drop them later. for now we leave them null

---

**2014**
"""

null_values_2014 = player_info_merged[(player_info_merged['season'] == 2014) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2014)

player_info_merged.loc[(player_info_merged['season'] == 2014) & (player_info_merged['week'] == 20) & (player_info_merged['team']=='CIN') & (player_info_merged['weather'].isnull()), 'weather'] = 'Snow'
player_info_merged.loc[(player_info_merged['season'] == 2014) & (player_info_merged['week'] == 20) & (player_info_merged['team']=='IND') & (player_info_merged['weather'].isnull()), 'weather'] = 'Snow'
player_info_merged.loc[(player_info_merged['season'] == 2014) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'




player_info_merged.loc[(player_info_merged['season'] == 2014) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2014) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2014) & (player_info_merged['week'] == 21) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2014 = player_info_merged[(player_info_merged['season'] == 2014) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2014)

"""

---

**2015**"""

null_values_2015 = player_info_merged[(player_info_merged['season'] == 2015) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2015)

player_info_merged.loc[(player_info_merged['season'] == 2015) & (player_info_merged['week'] == 20) & (player_info_merged['team']=='CIN') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2015) & (player_info_merged['week'] == 20) & (player_info_merged['team']=='PIT') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2015) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'




player_info_merged.loc[(player_info_merged['season'] == 2015) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2015) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2015) & (player_info_merged['week'] == 21) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2015 = player_info_merged[(player_info_merged['season'] == 2015) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2015)

"""

----
**2016**
"""

null_values_2016 = player_info_merged[(player_info_merged['season'] == 2016) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2016)

player_info_merged.loc[(player_info_merged['season'] == 2016) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2016) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2016) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2016) & (player_info_merged['week'] == 21) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2016 = player_info_merged[(player_info_merged['season'] == 2016) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2016)

"""

---
**2017**
"""

null_values_2017 = player_info_merged[(player_info_merged['season'] == 2017) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2017)

player_info_merged.loc[(player_info_merged['season'] == 2017) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2017) & (player_info_merged['week'] == 19) & (player_info_merged['team']=='NO') &  (player_info_merged['weather'].isnull()), 'weather'] = 'Snow'
player_info_merged.loc[(player_info_merged['season'] == 2017) & (player_info_merged['week'] == 19) & (player_info_merged['team']=='MIN') &  (player_info_merged['weather'].isnull()), 'weather'] = 'Snow'
player_info_merged.loc[(player_info_merged['season'] == 2017) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2017) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2017 = player_info_merged[(player_info_merged['season'] == 2017) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2017)

"""

---

**2018**"""

null_values_2018 = player_info_merged[(player_info_merged['season'] == 2018) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2018)

player_info_merged.loc[(player_info_merged['season'] == 2018) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2018) & (player_info_merged['week'] == 19) & (player_info_merged['team']=='IND') &  (player_info_merged['weather'].isnull()), 'weather'] = 'Snow'
player_info_merged.loc[(player_info_merged['season'] == 2018) & (player_info_merged['week'] == 19) & (player_info_merged['team']=='KC') &  (player_info_merged['weather'].isnull()), 'weather'] = 'Snow'
player_info_merged.loc[(player_info_merged['season'] == 2018) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2018) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'

null_values_2018 = player_info_merged[(player_info_merged['season'] == 2018) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2018)

"""

---
**2019**
"""

null_values_2019 = player_info_merged[(player_info_merged['season'] == 2019) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2019)

player_info_merged.loc[(player_info_merged['season'] == 2019) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2019) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2019) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2019 = player_info_merged[(player_info_merged['season'] == 2019) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2019)

"""

---

**2020**"""

null_values_2020 = player_info_merged[(player_info_merged['season'] == 2020) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2020)

player_info_merged.loc[(player_info_merged['season'] == 2020) & (player_info_merged['week'] == 18) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2020) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2020) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2020) & (player_info_merged['week'] == 21) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2020 = player_info_merged[(player_info_merged['season'] == 2020) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2020)

"""

---

**2021**"""

null_values_2021 = player_info_merged[(player_info_merged['season'] == 2021) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2021)

player_info_merged.loc[(player_info_merged['season'] == 2021) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2021) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2021) & (player_info_merged['week'] == 21) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'
player_info_merged.loc[(player_info_merged['season'] == 2021) & (player_info_merged['week'] == 22) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2021 = player_info_merged[(player_info_merged['season'] == 2021) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2021)

"""

---

**2022**"""

null_values_2022 = player_info_merged[(player_info_merged['season'] == 2022) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2022)

player_info_merged.loc[(player_info_merged['season'] == 2022) & (player_info_merged['week'] == 19) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'


player_info_merged.loc[(player_info_merged['season'] == 2022) & (player_info_merged['week'] == 20) &   (player_info_merged['team']=='KC') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2022) & (player_info_merged['week'] == 20) &   (player_info_merged['team']=='JAX') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2022) & (player_info_merged['week'] == 20) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'


player_info_merged.loc[(player_info_merged['season'] == 2022) & (player_info_merged['week'] == 21) &   (player_info_merged['team']=='PHI') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2022) & (player_info_merged['week'] == 21) &   (player_info_merged['team']=='SF') & (player_info_merged['weather'].isnull()), 'weather'] = 'Rain'
player_info_merged.loc[(player_info_merged['season'] == 2022) & (player_info_merged['week'] == 21) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

player_info_merged.loc[(player_info_merged['season'] == 2022) & (player_info_merged['week'] == 22) &  (player_info_merged['weather'].isnull()), 'weather'] = 'Dry'

null_values_2022 = player_info_merged[(player_info_merged['season'] == 2022) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2022)

"""

---

**2023**"""

null_values_2023 = player_info_merged[(player_info_merged['season'] == 2023) & (player_info_merged['weather'].isnull())][['season', 'week', 'team']]

# Display the result
print(null_values_2023)

print(player_info_merged)

for col in player_info_merged.columns:
    null_count = player_info_merged[col].isnull().sum()
    print(f"Column: {col}, Null Count: {null_count}")

"""the nulls are the nulls from 2013. we can drop"""

player_info_merged.dropna(subset=['weather'], inplace=True)

for col in player_info_merged.columns:
    null_count = player_info_merged[col].isnull().sum()
    print(f"Column: {col}, Null Count: {null_count}")

player_info_merged.to_csv('player_injury_age_weather_cleaned.csv', index=False)

print(player_info_merged)